ALTER TABLE public.supplier_orders
  ADD COLUMN IF NOT EXISTS closed_quantity numeric NOT NULL DEFAULT 0;

ALTER TABLE public.supplier_orders
  DROP CONSTRAINT IF EXISTS supplier_orders_closed_quantity_non_negative;

ALTER TABLE public.supplier_orders
  ADD CONSTRAINT supplier_orders_closed_quantity_non_negative
  CHECK (closed_quantity >= 0);

ALTER TABLE public.supplier_orders
  DROP CONSTRAINT IF EXISTS supplier_orders_received_closed_not_over_ordered;

ALTER TABLE public.supplier_orders
  ADD CONSTRAINT supplier_orders_received_closed_not_over_ordered
  CHECK (COALESCE(total_received, 0) + COALESCE(closed_quantity, 0) <= COALESCE(order_quantity, 0))
  NOT VALID;

CREATE TABLE IF NOT EXISTS public.supplier_order_balance_closures (
  closure_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id uuid NOT NULL REFERENCES public.organizations(id),
  supplier_order_id integer NOT NULL REFERENCES public.supplier_orders(order_id) ON DELETE CASCADE,
  purchase_order_id integer NOT NULL REFERENCES public.purchase_orders(purchase_order_id) ON DELETE CASCADE,
  quantity_closed numeric NOT NULL CHECK (quantity_closed > 0),
  reason_code text NOT NULL,
  notes text,
  created_by uuid REFERENCES auth.users(id),
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS supplier_order_balance_closures_org_idx
  ON public.supplier_order_balance_closures(org_id);

CREATE INDEX IF NOT EXISTS supplier_order_balance_closures_supplier_order_idx
  ON public.supplier_order_balance_closures(supplier_order_id);

CREATE TABLE IF NOT EXISTS public.supplier_order_balance_closure_allocations (
  allocation_closure_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id uuid NOT NULL REFERENCES public.organizations(id),
  closure_id bigint NOT NULL REFERENCES public.supplier_order_balance_closures(closure_id) ON DELETE CASCADE,
  supplier_order_customer_order_id integer REFERENCES public.supplier_order_customer_orders(id) ON DELETE SET NULL,
  customer_order_id integer REFERENCES public.orders(order_id) ON DELETE SET NULL,
  quantity_closed numeric NOT NULL CHECK (quantity_closed > 0),
  source_type text NOT NULL,
  source_order_id integer REFERENCES public.orders(order_id) ON DELETE SET NULL,
  notes text,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT supplier_order_balance_closure_allocations_source_type_chk
    CHECK (source_type IN (
      'free_stock',
      'offcut',
      'borrowed_from_order',
      'supplier_cancelled_replacement',
      'loss_writeoff',
      'unknown_needs_review'
    ))
);

CREATE INDEX IF NOT EXISTS supplier_order_balance_closure_allocations_org_idx
  ON public.supplier_order_balance_closure_allocations(org_id);

CREATE INDEX IF NOT EXISTS supplier_order_balance_closure_allocations_closure_idx
  ON public.supplier_order_balance_closure_allocations(closure_id);

ALTER TABLE public.supplier_order_balance_closures ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.supplier_order_balance_closure_allocations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS supplier_order_balance_closures_select_org_member
  ON public.supplier_order_balance_closures;
DROP POLICY IF EXISTS supplier_order_balance_closures_insert_org_member
  ON public.supplier_order_balance_closures;
DROP POLICY IF EXISTS supplier_order_balance_closures_update_org_member
  ON public.supplier_order_balance_closures;
DROP POLICY IF EXISTS supplier_order_balance_closures_delete_org_member
  ON public.supplier_order_balance_closures;

CREATE POLICY supplier_order_balance_closures_select_org_member
ON public.supplier_order_balance_closures
FOR SELECT
TO authenticated
USING (public.is_org_member(org_id));

CREATE POLICY supplier_order_balance_closures_insert_org_member
ON public.supplier_order_balance_closures
FOR INSERT
TO authenticated
WITH CHECK (public.is_org_member(org_id));

CREATE POLICY supplier_order_balance_closures_update_org_member
ON public.supplier_order_balance_closures
FOR UPDATE
TO authenticated
USING (public.is_org_member(org_id))
WITH CHECK (public.is_org_member(org_id));

CREATE POLICY supplier_order_balance_closures_delete_org_member
ON public.supplier_order_balance_closures
FOR DELETE
TO authenticated
USING (public.is_org_member(org_id));

DROP POLICY IF EXISTS supplier_order_balance_closure_allocations_select_org_member
  ON public.supplier_order_balance_closure_allocations;
DROP POLICY IF EXISTS supplier_order_balance_closure_allocations_insert_org_member
  ON public.supplier_order_balance_closure_allocations;
DROP POLICY IF EXISTS supplier_order_balance_closure_allocations_update_org_member
  ON public.supplier_order_balance_closure_allocations;
DROP POLICY IF EXISTS supplier_order_balance_closure_allocations_delete_org_member
  ON public.supplier_order_balance_closure_allocations;

CREATE POLICY supplier_order_balance_closure_allocations_select_org_member
ON public.supplier_order_balance_closure_allocations
FOR SELECT
TO authenticated
USING (public.is_org_member(org_id));

CREATE POLICY supplier_order_balance_closure_allocations_insert_org_member
ON public.supplier_order_balance_closure_allocations
FOR INSERT
TO authenticated
WITH CHECK (public.is_org_member(org_id));

CREATE POLICY supplier_order_balance_closure_allocations_update_org_member
ON public.supplier_order_balance_closure_allocations
FOR UPDATE
TO authenticated
USING (public.is_org_member(org_id))
WITH CHECK (public.is_org_member(org_id));

CREATE POLICY supplier_order_balance_closure_allocations_delete_org_member
ON public.supplier_order_balance_closure_allocations
FOR DELETE
TO authenticated
USING (public.is_org_member(org_id));

-- Ledger rows are written through close_supplier_order_balance only.
-- Normal users may read them, but may not directly insert, update, or delete audit history.
DROP POLICY IF EXISTS supplier_order_balance_closures_insert_org_member
  ON public.supplier_order_balance_closures;
DROP POLICY IF EXISTS supplier_order_balance_closures_update_org_member
  ON public.supplier_order_balance_closures;
DROP POLICY IF EXISTS supplier_order_balance_closures_delete_org_member
  ON public.supplier_order_balance_closures;
DROP POLICY IF EXISTS supplier_order_balance_closure_allocations_insert_org_member
  ON public.supplier_order_balance_closure_allocations;
DROP POLICY IF EXISTS supplier_order_balance_closure_allocations_update_org_member
  ON public.supplier_order_balance_closure_allocations;
DROP POLICY IF EXISTS supplier_order_balance_closure_allocations_delete_org_member
  ON public.supplier_order_balance_closure_allocations;

CREATE OR REPLACE FUNCTION public.close_supplier_order_balance(
  p_supplier_order_id integer,
  p_quantity numeric,
  p_reason_code text,
  p_notes text DEFAULT NULL,
  p_reconciliation jsonb DEFAULT '[]'::jsonb
)
RETURNS TABLE(
  closure_id bigint,
  supplier_order_id integer,
  quantity_closed numeric,
  closed_quantity numeric,
  outstanding_quantity numeric
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_order record;
  v_existing_closed numeric;
  v_outstanding numeric;
  v_reconciliation_sum numeric;
  v_closure_id bigint;
  v_current_user_id uuid := auth.uid();
  v_cancelled_status_id integer;
BEGIN
  IF p_supplier_order_id IS NULL THEN
    RAISE EXCEPTION 'close_supplier_order_balance: supplier order id is required';
  END IF;

  IF p_quantity IS NULL OR p_quantity <= 0 THEN
    RAISE EXCEPTION 'close_supplier_order_balance: quantity must be greater than zero';
  END IF;

  IF p_reason_code IS NULL OR trim(p_reason_code) = '' THEN
    RAISE EXCEPTION 'close_supplier_order_balance: reason code is required';
  END IF;

  IF p_reconciliation IS NULL OR jsonb_typeof(p_reconciliation) <> 'array' THEN
    RAISE EXCEPTION 'close_supplier_order_balance: reconciliation must be an array';
  END IF;

  IF jsonb_array_length(p_reconciliation) = 0 THEN
    RAISE EXCEPTION 'close_supplier_order_balance: reconciliation must include at least one row';
  END IF;

  SELECT
    so.order_id,
    so.org_id,
    so.purchase_order_id,
    so.order_quantity,
    COALESCE(so.total_received, 0) AS total_received,
    COALESCE(so.closed_quantity, 0) AS closed_quantity,
    so.status_id,
    sc.component_id,
    c.internal_code
  INTO v_order
  FROM public.supplier_orders so
  LEFT JOIN public.suppliercomponents sc ON sc.supplier_component_id = so.supplier_component_id
  LEFT JOIN public.components c ON c.component_id = sc.component_id
  WHERE so.order_id = p_supplier_order_id
  FOR UPDATE OF so;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'close_supplier_order_balance: supplier order % not found', p_supplier_order_id;
  END IF;

  IF auth.role() <> 'service_role' AND NOT public.is_org_member(v_order.org_id) THEN
    RAISE EXCEPTION 'close_supplier_order_balance: access denied';
  END IF;

  IF v_order.org_id IS NULL THEN
    RAISE EXCEPTION 'close_supplier_order_balance: supplier order % is missing org_id', p_supplier_order_id;
  END IF;

  IF v_order.purchase_order_id IS NULL THEN
    RAISE EXCEPTION 'close_supplier_order_balance: supplier order % is not linked to a purchase order', p_supplier_order_id;
  END IF;

  SELECT status_id
  INTO v_cancelled_status_id
  FROM public.supplier_order_statuses
  WHERE status_name = 'Cancelled'
  LIMIT 1;

  IF v_order.status_id = v_cancelled_status_id THEN
    RAISE EXCEPTION 'close_supplier_order_balance: cancelled supplier orders cannot be closed';
  END IF;

  v_existing_closed := v_order.closed_quantity;
  v_outstanding := GREATEST(COALESCE(v_order.order_quantity, 0) - v_order.total_received - v_existing_closed, 0);

  IF p_quantity > v_outstanding THEN
    RAISE EXCEPTION 'close_supplier_order_balance: quantity % exceeds outstanding quantity %',
      p_quantity, v_outstanding;
  END IF;

  IF p_quantity > 0 AND v_outstanding = 0 THEN
    RAISE EXCEPTION 'close_supplier_order_balance: supplier order % has no outstanding balance', p_supplier_order_id;
  END IF;

  IF EXISTS (
    SELECT 1
    FROM jsonb_array_elements(p_reconciliation) AS item
    WHERE COALESCE((item->>'quantity_closed')::numeric, 0) <= 0
  ) THEN
    RAISE EXCEPTION 'close_supplier_order_balance: each reconciliation quantity must be greater than zero';
  END IF;

  SELECT COALESCE(SUM((item->>'quantity_closed')::numeric), 0)
  INTO v_reconciliation_sum
  FROM jsonb_array_elements(p_reconciliation) AS item
  WHERE COALESCE((item->>'quantity_closed')::numeric, 0) > 0;

  IF v_reconciliation_sum <> p_quantity THEN
    RAISE EXCEPTION 'close_supplier_order_balance: reconciliation quantity % must equal closed quantity %',
      v_reconciliation_sum, p_quantity;
  END IF;

  IF EXISTS (
    SELECT 1
    FROM jsonb_array_elements(p_reconciliation) AS item
    WHERE COALESCE(item->>'source_type', '') NOT IN (
      'free_stock',
      'offcut',
      'borrowed_from_order',
      'supplier_cancelled_replacement',
      'loss_writeoff',
      'unknown_needs_review'
    )
  ) THEN
    RAISE EXCEPTION 'close_supplier_order_balance: reconciliation contains an invalid source type';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM jsonb_array_elements(p_reconciliation) AS item
    WHERE item->>'source_type' = 'borrowed_from_order'
      AND NULLIF(item->>'source_order_id', '') IS NULL
  ) THEN
    RAISE EXCEPTION 'close_supplier_order_balance: borrowed_from_order rows require source_order_id';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM jsonb_array_elements(p_reconciliation) AS item
    WHERE NULLIF(item->>'supplier_order_customer_order_id', '') IS NULL
      AND NULLIF(item->>'customer_order_id', '') IS NOT NULL
  ) THEN
    RAISE EXCEPTION 'close_supplier_order_balance: customer_order_id requires supplier_order_customer_order_id';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM jsonb_array_elements(p_reconciliation) AS item
    LEFT JOIN public.supplier_order_customer_orders soco
      ON soco.id = NULLIF(item->>'supplier_order_customer_order_id', '')::integer
     AND soco.supplier_order_id = v_order.order_id
     AND soco.org_id = v_order.org_id
    WHERE NULLIF(item->>'supplier_order_customer_order_id', '') IS NOT NULL
      AND soco.id IS NULL
  ) THEN
    RAISE EXCEPTION 'close_supplier_order_balance: reconciliation contains allocations not tied to supplier order %', p_supplier_order_id;
  END IF;

  IF EXISTS (
    SELECT 1
    FROM jsonb_array_elements(p_reconciliation) AS item
    JOIN public.supplier_order_customer_orders soco
      ON soco.id = NULLIF(item->>'supplier_order_customer_order_id', '')::integer
    WHERE NULLIF(item->>'supplier_order_customer_order_id', '') IS NOT NULL
      AND NULLIF(item->>'customer_order_id', '') IS NOT NULL
      AND soco.order_id IS DISTINCT FROM NULLIF(item->>'customer_order_id', '')::integer
  ) THEN
    RAISE EXCEPTION 'close_supplier_order_balance: reconciliation customer order does not match allocation';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM jsonb_array_elements(p_reconciliation) AS item
    LEFT JOIN public.orders source_order
      ON source_order.order_id = NULLIF(item->>'source_order_id', '')::integer
     AND source_order.org_id = v_order.org_id
    WHERE NULLIF(item->>'source_order_id', '') IS NOT NULL
      AND source_order.order_id IS NULL
  ) THEN
    RAISE EXCEPTION 'close_supplier_order_balance: source_order_id must belong to the same organization';
  END IF;

  INSERT INTO public.supplier_order_balance_closures (
    org_id,
    supplier_order_id,
    purchase_order_id,
    quantity_closed,
    reason_code,
    notes,
    created_by,
    metadata
  )
  VALUES (
    v_order.org_id,
    v_order.order_id,
    v_order.purchase_order_id,
    p_quantity,
    p_reason_code,
    NULLIF(trim(COALESCE(p_notes, '')), ''),
    v_current_user_id,
    jsonb_build_object(
      'component_id', v_order.component_id,
      'component_code', v_order.internal_code,
      'previous_closed_quantity', v_existing_closed,
      'previous_outstanding_quantity', v_outstanding
    )
  )
  RETURNING supplier_order_balance_closures.closure_id INTO v_closure_id;

  INSERT INTO public.supplier_order_balance_closure_allocations (
    org_id,
    closure_id,
    supplier_order_customer_order_id,
    customer_order_id,
    quantity_closed,
    source_type,
    source_order_id,
    notes,
    metadata
  )
  SELECT
    v_order.org_id,
    v_closure_id,
    soco.id,
    soco.order_id,
    (item->>'quantity_closed')::numeric,
    item->>'source_type',
    NULLIF(item->>'source_order_id', '')::integer,
    NULLIF(trim(COALESCE(item->>'notes', '')), ''),
    COALESCE(item->'metadata', '{}'::jsonb)
  FROM jsonb_array_elements(p_reconciliation) AS item
  LEFT JOIN public.supplier_order_customer_orders soco
    ON soco.id = NULLIF(item->>'supplier_order_customer_order_id', '')::integer
   AND soco.supplier_order_id = v_order.order_id
   AND soco.org_id = v_order.org_id
  WHERE COALESCE((item->>'quantity_closed')::numeric, 0) > 0;

  UPDATE public.supplier_orders
  SET closed_quantity = v_existing_closed + p_quantity
  WHERE order_id = v_order.order_id;

  INSERT INTO public.purchase_order_activity (
    org_id,
    purchase_order_id,
    action_type,
    description,
    metadata,
    performed_by
  )
  VALUES (
    v_order.org_id,
    v_order.purchase_order_id,
    'line_balance_closed',
    'Closed outstanding balance of ' || p_quantity || ' for supplier order #' || v_order.order_id,
    jsonb_build_object(
      'supplier_order_id', v_order.order_id,
      'closure_id', v_closure_id,
      'quantity_closed', p_quantity,
      'reason_code', p_reason_code,
      'reconciliation', p_reconciliation
    ),
    v_current_user_id
  );

  RETURN QUERY
  SELECT
    v_closure_id,
    v_order.order_id,
    p_quantity,
    v_existing_closed + p_quantity,
    GREATEST(COALESCE(v_order.order_quantity, 0) - v_order.total_received - v_existing_closed - p_quantity, 0);
END;
$function$;

REVOKE ALL ON FUNCTION public.close_supplier_order_balance(integer, numeric, text, text, jsonb) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.close_supplier_order_balance(integer, numeric, text, text, jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.close_supplier_order_balance(integer, numeric, text, text, jsonb) TO service_role;
