// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/bypass/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bypass/orders">> = Specific
  const handler = {} as typeof import("../../../app/bypass/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/bypass/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bypass">> = Specific
  const handler = {} as typeof import("../../../app/bypass/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/collections/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/collections/[id]">> = Specific
  const handler = {} as typeof import("../../../app/collections/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/collections/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/collections">> = Specific
  const handler = {} as typeof import("../../../app/collections/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/customers/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customers/[id]/edit">> = Specific
  const handler = {} as typeof import("../../../app/customers/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/customers/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customers/[id]">> = Specific
  const handler = {} as typeof import("../../../app/customers/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/customers/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customers/new">> = Specific
  const handler = {} as typeof import("../../../app/customers/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/customers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customers">> = Specific
  const handler = {} as typeof import("../../../app/customers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/cutlist/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cutlist">> = Specific
  const handler = {} as typeof import("../../../app/cutlist/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/debug/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/debug">> = Specific
  const handler = {} as typeof import("../../../app/debug/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/inventory/components/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory/components/[id]">> = Specific
  const handler = {} as typeof import("../../../app/inventory/components/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/inventory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory">> = Specific
  const handler = {} as typeof import("../../../app/inventory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/labor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/labor">> = Specific
  const handler = {} as typeof import("../../../app/labor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/orders/[orderId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/[orderId]">> = Specific
  const handler = {} as typeof import("../../../app/orders/[orderId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/orders/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/new">> = Specific
  const handler = {} as typeof import("../../../app/orders/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders">> = Specific
  const handler = {} as typeof import("../../../app/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/pdf-quote-demo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pdf-quote-demo">> = Specific
  const handler = {} as typeof import("../../../app/pdf-quote-demo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/pdf-test-client/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pdf-test-client">> = Specific
  const handler = {} as typeof import("../../../app/pdf-test-client/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/pdf-test.bak/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pdf-test.bak">> = Specific
  const handler = {} as typeof import("../../../app/pdf-test.bak/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/products/[productId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/products/[productId]">> = Specific
  const handler = {} as typeof import("../../../app/products/[productId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/products/options/sets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/products/options/sets">> = Specific
  const handler = {} as typeof import("../../../app/products/options/sets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/products">> = Specific
  const handler = {} as typeof import("../../../app/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/purchasing/[orderId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchasing/[orderId]">> = Specific
  const handler = {} as typeof import("../../../app/purchasing/[orderId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/purchasing/multi-order/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchasing/multi-order">> = Specific
  const handler = {} as typeof import("../../../app/purchasing/multi-order/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/purchasing/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchasing/new">> = Specific
  const handler = {} as typeof import("../../../app/purchasing/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/purchasing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchasing">> = Specific
  const handler = {} as typeof import("../../../app/purchasing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/purchasing/purchase-orders/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchasing/purchase-orders/[id]">> = Specific
  const handler = {} as typeof import("../../../app/purchasing/purchase-orders/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/purchasing/purchase-orders/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchasing/purchase-orders/new">> = Specific
  const handler = {} as typeof import("../../../app/purchasing/purchase-orders/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/purchasing/purchase-orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchasing/purchase-orders">> = Specific
  const handler = {} as typeof import("../../../app/purchasing/purchase-orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/quotes/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/quotes/[id]">> = Specific
  const handler = {} as typeof import("../../../app/quotes/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/quotes/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/quotes/new">> = Specific
  const handler = {} as typeof import("../../../app/quotes/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/quotes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/quotes">> = Specific
  const handler = {} as typeof import("../../../app/quotes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/settings/option-sets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/option-sets">> = Specific
  const handler = {} as typeof import("../../../app/settings/option-sets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../../app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/staff/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/staff/[id]/edit">> = Specific
  const handler = {} as typeof import("../../../app/staff/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/staff/hours/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/staff/hours">> = Specific
  const handler = {} as typeof import("../../../app/staff/hours/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/staff/job-cards/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/staff/job-cards/new">> = Specific
  const handler = {} as typeof import("../../../app/staff/job-cards/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/staff/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/staff/new">> = Specific
  const handler = {} as typeof import("../../../app/staff/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/staff/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/staff">> = Specific
  const handler = {} as typeof import("../../../app/staff/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/staff/payroll/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/staff/payroll">> = Specific
  const handler = {} as typeof import("../../../app/staff/payroll/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/suppliers/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/suppliers/[id]">> = Specific
  const handler = {} as typeof import("../../../app/suppliers/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/suppliers/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/suppliers/new">> = Specific
  const handler = {} as typeof import("../../../app/suppliers/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/suppliers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/suppliers">> = Specific
  const handler = {} as typeof import("../../../app/suppliers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/test-layout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test-layout">> = Specific
  const handler = {} as typeof import("../../../app/test-layout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/test-router/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test-router/[id]">> = Specific
  const handler = {} as typeof import("../../../app/test-router/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/test-router/order-detail-animated/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test-router/order-detail-animated">> = Specific
  const handler = {} as typeof import("../../../app/test-router/order-detail-animated/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/test-router/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test-router">> = Specific
  const handler = {} as typeof import("../../../app/test-router/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/test-styles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test-styles">> = Specific
  const handler = {} as typeof import("../../../app/test-styles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/todos/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/todos/[id]">> = Specific
  const handler = {} as typeof import("../../../app/todos/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/todos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/todos">> = Specific
  const handler = {} as typeof import("../../../app/todos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/check-rls/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/check-rls">> = Specific
  const handler = {} as typeof import("../../../app/api/check-rls/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/collections/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/collections/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/collections/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/collections/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/collections">> = Specific
  const handler = {} as typeof import("../../../app/api/collections/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/components/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/components">> = Specific
  const handler = {} as typeof import("../../../app/api/components/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/create-test-quote/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/create-test-quote">> = Specific
  const handler = {} as typeof import("../../../app/api/create-test-quote/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/debug-quote/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug-quote">> = Specific
  const handler = {} as typeof import("../../../app/api/debug-quote/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/debug/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug">> = Specific
  const handler = {} as typeof import("../../../app/api/debug/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/dev/update-quote-item/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dev/update-quote-item">> = Specific
  const handler = {} as typeof import("../../../app/api/dev/update-quote-item/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/entity-links/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/entity-links">> = Specific
  const handler = {} as typeof import("../../../app/api/entity-links/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../../app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/inventory/components/[componentId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/components/[componentId]">> = Specific
  const handler = {} as typeof import("../../../app/api/inventory/components/[componentId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/list-quotes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/list-quotes">> = Specific
  const handler = {} as typeof import("../../../app/api/list-quotes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/migrations/run/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/migrations/run">> = Specific
  const handler = {} as typeof import("../../../app/api/migrations/run/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/option-sets/[setId]/groups/[groupId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/option-sets/[setId]/groups/[groupId]">> = Specific
  const handler = {} as typeof import("../../../app/api/option-sets/[setId]/groups/[groupId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/option-sets/[setId]/groups/[groupId]/values/[valueId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/option-sets/[setId]/groups/[groupId]/values/[valueId]">> = Specific
  const handler = {} as typeof import("../../../app/api/option-sets/[setId]/groups/[groupId]/values/[valueId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/option-sets/[setId]/groups/[groupId]/values/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/option-sets/[setId]/groups/[groupId]/values">> = Specific
  const handler = {} as typeof import("../../../app/api/option-sets/[setId]/groups/[groupId]/values/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/option-sets/[setId]/groups/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/option-sets/[setId]/groups">> = Specific
  const handler = {} as typeof import("../../../app/api/option-sets/[setId]/groups/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/option-sets/[setId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/option-sets/[setId]">> = Specific
  const handler = {} as typeof import("../../../app/api/option-sets/[setId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/option-sets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/option-sets">> = Specific
  const handler = {} as typeof import("../../../app/api/option-sets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/orders/[orderId]/add-products/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/[orderId]/add-products">> = Specific
  const handler = {} as typeof import("../../../app/api/orders/[orderId]/add-products/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/orders/[orderId]/consume-fg/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/[orderId]/consume-fg">> = Specific
  const handler = {} as typeof import("../../../app/api/orders/[orderId]/consume-fg/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/orders/[orderId]/fg-reservations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/[orderId]/fg-reservations">> = Specific
  const handler = {} as typeof import("../../../app/api/orders/[orderId]/fg-reservations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/orders/[orderId]/release-fg/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/[orderId]/release-fg">> = Specific
  const handler = {} as typeof import("../../../app/api/orders/[orderId]/release-fg/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/orders/[orderId]/reserve-fg/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/[orderId]/reserve-fg">> = Specific
  const handler = {} as typeof import("../../../app/api/orders/[orderId]/reserve-fg/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/orders/[orderId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/[orderId]">> = Specific
  const handler = {} as typeof import("../../../app/api/orders/[orderId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/orders/from-quote/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/from-quote">> = Specific
  const handler = {} as typeof import("../../../app/api/orders/from-quote/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/process-all/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/process-all">> = Specific
  const handler = {} as typeof import("../../../app/api/process-all/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/process-clock-events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/process-clock-events">> = Specific
  const handler = {} as typeof import("../../../app/api/process-clock-events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/products/[productId]/add-fg/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/[productId]/add-fg">> = Specific
  const handler = {} as typeof import("../../../app/api/products/[productId]/add-fg/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/products/[productId]/bom/apply-collection/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/[productId]/bom/apply-collection">> = Specific
  const handler = {} as typeof import("../../../app/api/products/[productId]/bom/apply-collection/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/products/[productId]/bom/apply-product/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/[productId]/bom/apply-product">> = Specific
  const handler = {} as typeof import("../../../app/api/products/[productId]/bom/apply-product/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/products/[productId]/bom/attach-product/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/[productId]/bom/attach-product">> = Specific
  const handler = {} as typeof import("../../../app/api/products/[productId]/bom/attach-product/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/products/[productId]/effective-bol/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/[productId]/effective-bol">> = Specific
  const handler = {} as typeof import("../../../app/api/products/[productId]/effective-bol/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/products/[productId]/effective-bom/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/[productId]/effective-bom">> = Specific
  const handler = {} as typeof import("../../../app/api/products/[productId]/effective-bom/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/products/[productId]/option-sets/[linkId]/groups/[groupId]/overlay/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/[productId]/option-sets/[linkId]/groups/[groupId]/overlay">> = Specific
  const handler = {} as typeof import("../../../app/api/products/[productId]/option-sets/[linkId]/groups/[groupId]/overlay/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/products/[productId]/option-sets/[linkId]/groups/[groupId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/[productId]/option-sets/[linkId]/groups/[groupId]">> = Specific
  const handler = {} as typeof import("../../../app/api/products/[productId]/option-sets/[linkId]/groups/[groupId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/products/[productId]/option-sets/[linkId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/[productId]/option-sets/[linkId]">> = Specific
  const handler = {} as typeof import("../../../app/api/products/[productId]/option-sets/[linkId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/products/[productId]/option-sets/[linkId]/values/[valueId]/overlay/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/[productId]/option-sets/[linkId]/values/[valueId]/overlay">> = Specific
  const handler = {} as typeof import("../../../app/api/products/[productId]/option-sets/[linkId]/values/[valueId]/overlay/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/products/[productId]/option-sets/[linkId]/values/[valueId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/[productId]/option-sets/[linkId]/values/[valueId]">> = Specific
  const handler = {} as typeof import("../../../app/api/products/[productId]/option-sets/[linkId]/values/[valueId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/products/[productId]/option-sets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/[productId]/option-sets">> = Specific
  const handler = {} as typeof import("../../../app/api/products/[productId]/option-sets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/products/[productId]/options/bom/[bomId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/[productId]/options/bom/[bomId]">> = Specific
  const handler = {} as typeof import("../../../app/api/products/[productId]/options/bom/[bomId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/products/[productId]/options/groups/[groupId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/[productId]/options/groups/[groupId]">> = Specific
  const handler = {} as typeof import("../../../app/api/products/[productId]/options/groups/[groupId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/products/[productId]/options/groups/[groupId]/values/[valueId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/[productId]/options/groups/[groupId]/values/[valueId]">> = Specific
  const handler = {} as typeof import("../../../app/api/products/[productId]/options/groups/[groupId]/values/[valueId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/products/[productId]/options/groups/[groupId]/values/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/[productId]/options/groups/[groupId]/values">> = Specific
  const handler = {} as typeof import("../../../app/api/products/[productId]/options/groups/[groupId]/values/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/products/[productId]/options/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/[productId]/options">> = Specific
  const handler = {} as typeof import("../../../app/api/products/[productId]/options/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/products/[productId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/[productId]">> = Specific
  const handler = {} as typeof import("../../../app/api/products/[productId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/products/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products">> = Specific
  const handler = {} as typeof import("../../../app/api/products/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/profiles/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profiles">> = Specific
  const handler = {} as typeof import("../../../app/api/profiles/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/quote-items/[id]/cutlist/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quote-items/[id]/cutlist/export">> = Specific
  const handler = {} as typeof import("../../../app/api/quote-items/[id]/cutlist/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/quote-items/[id]/cutlist/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quote-items/[id]/cutlist">> = Specific
  const handler = {} as typeof import("../../../app/api/quote-items/[id]/cutlist/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/quotes/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quotes/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/quotes/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/quotes/[id]/send-email/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quotes/[id]/send-email">> = Specific
  const handler = {} as typeof import("../../../app/api/quotes/[id]/send-email/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/quotes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quotes">> = Specific
  const handler = {} as typeof import("../../../app/api/quotes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/send-purchase-order-email/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/send-purchase-order-email">> = Specific
  const handler = {} as typeof import("../../../app/api/send-purchase-order-email/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings">> = Specific
  const handler = {} as typeof import("../../../app/api/settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/supplier-components/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/supplier-components">> = Specific
  const handler = {} as typeof import("../../../app/api/supplier-components/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/test-db-schema/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/test-db-schema">> = Specific
  const handler = {} as typeof import("../../../app/api/test-db-schema/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/todos/[todoId]/acknowledge/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/todos/[todoId]/acknowledge">> = Specific
  const handler = {} as typeof import("../../../app/api/todos/[todoId]/acknowledge/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/todos/[todoId]/attachments/[attachmentId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/todos/[todoId]/attachments/[attachmentId]">> = Specific
  const handler = {} as typeof import("../../../app/api/todos/[todoId]/attachments/[attachmentId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/todos/[todoId]/attachments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/todos/[todoId]/attachments">> = Specific
  const handler = {} as typeof import("../../../app/api/todos/[todoId]/attachments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/todos/[todoId]/comments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/todos/[todoId]/comments">> = Specific
  const handler = {} as typeof import("../../../app/api/todos/[todoId]/comments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/todos/[todoId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/todos/[todoId]">> = Specific
  const handler = {} as typeof import("../../../app/api/todos/[todoId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/todos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/todos">> = Specific
  const handler = {} as typeof import("../../../app/api/todos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/collections/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/collections">> = Specific
  const handler = {} as typeof import("../../../app/collections/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/customers/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/customers">> = Specific
  const handler = {} as typeof import("../../../app/customers/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/inventory/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/inventory">> = Specific
  const handler = {} as typeof import("../../../app/inventory/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/orders/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/orders">> = Specific
  const handler = {} as typeof import("../../../app/orders/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/products/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/products">> = Specific
  const handler = {} as typeof import("../../../app/products/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/purchasing/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/purchasing">> = Specific
  const handler = {} as typeof import("../../../app/purchasing/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/quotes/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/quotes">> = Specific
  const handler = {} as typeof import("../../../app/quotes/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/settings/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../../app/settings/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/staff/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/staff">> = Specific
  const handler = {} as typeof import("../../../app/staff/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/suppliers/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/suppliers">> = Specific
  const handler = {} as typeof import("../../../app/suppliers/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
